version: "3.9"

services:

  nodered:
    image: nodered/node-red:4.1.7
    environment:
      - TZ=America/Argentina/BuenosAires
    container_name: nodered
    volumes:
      - ./nodered_data:/data
    expose:
      - 1880

  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - nodered
      - adminer
      

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPWD}
      #MYSQL_ROOT_PASSWORD: iwei4a2o25

    expose:
      - 3306
    ports:
      - "10.35.237.181:3306:3306"
     # - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql   

  adminer:
    image: adminer
    restart: always
    expose:
      - 8080

